### ISSUE TITLE
Consider renaming zoxide.py to __init__.py

### ISSUE THREAD

**Issue by ajeetdsouza** [jchook/ranger-zoxide#1]
Hey, thanks for maintaining ranger-zoxide!

Ranger now supports plugin directories, allowing one to simply clone entire Git repositories straight into your plugin directory. This makes both installating and updating plugins a lot easier.

For this, your directory needs to be a proper Python package -- to do this, you can simply rename `zoxide.py` to `__init__.py`.

**Comment by jchook** [comment]
Thanks for suggesting this change. Much better.

Do you know when ranger began supporting this? I don't see a note in the [CHANGELOG.md](https://github.com/ranger/ranger/blob/master/CHANGELOG.md).

**Comment by ajeetdsouza** [comment]
The change happened in this PR: https://github.com/ranger/ranger/pull/1418

I got a request to change this in the official zoxide repo (https://github.com/ajeetdsouza/zoxide/issues/215). However, I don't use ranger myself, and I noticed that you've made some improvements in your repo - so I thought I'd just remove the ranger script from my repo and link to yours instead. Hope that's okay!

**Comment by jchook** [comment]
Great, thank you! Merged 🎉

PS thank you for making zoxide!
