### ISSUE TITLE
zi in ranger does not jump to directory

### ISSUE THREAD

**Issue by c02y** [jchook/ranger-zoxide#10]
When I use `:zi dir` inside ranger, it uses the fzf to choose the right path, but after I hit `Enter`, it doesn't jump to the directory.

`zi` inside my shell works OK.

**Comment by jchook** [comment]
Thanks for the bug report. Perhaps related to #9

**Comment by jchook** [comment]
@c02y can you give more information about your environment? `zi` works great for me with latest master and this setup:

```sh
➜ uname -r
5.13.13_1

➜ ranger --version
ranger version: ranger 1.9.3
Python version: 3.9.6 (default, Jul  6 2021, 18:29:50) [GCC 10.2.1 20201203]
Locale: en_US.UTF-8

➜ zoxide --version
zoxide v0.7.3
```

**Comment by c02y** [comment]
```
$ unam -r
5.14.3-1-MANJARO

$ ranger --version
ranger version: ranger-master
Python version: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Locale: en_US.UTF-8

$ zoxide --version
zoxide v0.7.5
```

Ranger is manually installed from git repo, commit is d617dd208 which is the latest commit.

**Comment by jchook** [comment]
Still unable to reproduce.

Here's a Dockerfile I used to verify it works for me on the latest master on Debian:

```dockerfile
FROM debian
RUN apt-get update && apt-get install -y python3 python3-setuptools git fzf zoxide make
RUN git clone https://github.com/ranger/ranger.git \
  && cd /ranger \
  && make install \
  && mkdir -p ~/.config/ranger/plugins \
  && zoxide add ~/.config/ranger \
  && zoxide add /ranger \
  && git clone https://github.com/jchook/ranger-zoxide.git ~/.config/ranger/plugins/ranger-zoxide

CMD ["ranger"]
```

To build and run:

```sh
docker build -t ranger .
docker run -it ranger
```

Once in ranger, I ran `:zi ranger` to get an interactive list of two possible directories, and pressing enter worked.

https://user-images.githubusercontent.com/193530/135337098-09b20575-3d52-4045-a8fa-42ae4a377fc4.mp4

**Comment by c02y** [comment]
Don't know why, it works again. Sorry.

Don't remember how I tested it back then.
