### ISSUE TITLE
`--print0` in `_ZO_FZF_OPTS` will make zi unusable in ranger

### ISSUE THREAD

**Issue by c02y** [jchook/ranger-zoxide#11]
Long time ago I posted an issue https://github.com/jchook/ranger-zoxide/issues/10

then finally I know why it doesn't work.

I got `set -gx _ZO_FZF_OPTS "-1 -0 --reverse --print0"` in my fish shell config

and I found that `--print0` will make the `zi` unusable in ranger.

**Comment by jchook** [comment]
Do you have a recommended fix?

Should we override the value of `_ZO_FZF_OPTS`?

**Comment by c02y** [comment]
I removed `--print0` in `_ZO_FZF_OPTS`.
