### ISSUE TITLE
Provide configuration option for command name

### ISSUE THREAD

**Issue by jdsee** [jchook/ranger-zoxide#12]
I prefer `:j` over `:z` to trigger Zoxide and would like to be able to configure the command in some way. Zoxide also allows to configure the command with `zoxide init --cmd j`.

I could try to implement it if there's interest in it.

**Comment by jchook** [comment]
You are welcome to submit a PR.

**Comment by c02y** [comment]
Why wouldn't you just use binding such as:
```
map cz console zi%space
```

**Comment by jchook** [comment]
Sorry if I am being dense, but... does that solve the issue?
