### ISSUE TITLE
mligy

### ISSUE THREAD

**Issue by mohamedmligy** [jchook/ranger-zoxide#15]
[submodule ".config/ranger/plugins/zoxide"]
	path = .config/ranger/plugins/zoxide
	url = git@github.com:jchook/ranger-zoxide.git
[submodule ".hammerspoon/stackline"]
	path = .hammerspoon/stackline
	url = git@github.com:AdamWagner/stackline.git
<details><summary>Details</summary>
<p>

</p>
</details>

**Comment by jchook** [comment]
?

**Comment by mohamedmligy** [comment]
https://www.facebook.com/groups/639561253604617/permalink/650228469204562/
