### ISSUE TITLE
 Add .gitignore file that ignores the __pycache__ directory #11 

### ISSUE THREAD

**Issue by Anomalocaridid** [jchook/ranger-zoxide#3]
When using plugins by cloning their repos into Ranger's plugins folder, a directory named \_\_pycache__ is created. Since it is currently not ignored, git thinks that my local copy of the ranger-zoxide repo has been modified. This isn't a very big problem, but it is somewhat annoying and I would appreciate a .gitignore file that ignores \_\_pycache__.

**Comment by jchook** [comment]
PRs welcome
