### ISSUE TITLE
Merge with another plugin?

### ISSUE THREAD

**Issue by fdw** [jchook/ranger-zoxide#6]
Hi,

when I migrated to zoxide, I also migrated my old ranger-autojump plugin to [ranger-zoxide](https://github.com/fdw/ranger-zoxide). As you can guess, I now found your plugin, and I'm wondering if it makes sense to merge the two? The code differs just a bit, and mine also offers a zsh plugin to easily invoke ranger in a certain directory. What do you think?

**Comment by jchook** [comment]
Nice! Hey @fdw thanks for the suggestion.

Do you think it makes sense to ship your zsh plugin as a separate repo, so it works more easily with zsh plugin managers? I'd be happy to link to it from the README.

> The code differs just a bit

PRs are absolutely welcome.

**Comment by fdw** [comment]
> Do you think it makes sense to ship your zsh plugin as a separate repo, so it works more easily with zsh plugin managers? I'd be happy to link to it from the README.

It already works that way 🙂 The plugin managers look for a `.plugin.zsh` file, which the repo provides.
As both improve the combination of ranger and zoxide, I think it makes sense to keep it in the same repo.

> PRs are absolutely welcome.
I think I'll open some, and then you can decide if you like the changes 😉

**Comment by jchook** [comment]
Merged 🎉

**Comment by fdw** [comment]
So, what do you want to do about the zsh-Plugin? Should we also migrate that here, to have everything in one place?
